spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/springboot"
    username: "yuri"
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"